name: Check Markdown links
# https://github.com/marketplace/actions/markdown-link-check
on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 12 * * 0-5

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
#        config-file: 'warez_config.json'
#        folder-path: 'docs/markdown_files
